### ISSUE TITLE
Feature- Add texts explaining the sorting process as the animation is occuring

### ISSUE THREAD

**Issue by Soumelee** [Soumelee/SortingVisualizer#6]

**Comment by anamikapanda** [comment]
[Learn to code — free 3,000-hour curriculum](https://www.freecodecamp.org/)

DECEMBER 4, 2019
/
[#ALGORITHMS](https://www.freecodecamp.org/news/tag/algorithms/)
Sorting Algorithms Explained with Examples in JavaScript, Python, Java, and C++
What is a Sorting Algorithm?
Sorting algorithms are a set of instructions that take an array or list as an input and arrange the items into a particular order.

Sorts are most commonly in numerical or a form of alphabetical (or lexicographical) order, and can be in ascending (A-Z, 0-9) or descending (Z-A, 9-0) order.

Why Sorting Algorithms are Important
Since they can often reduce the complexity of a problem, sorting algorithms are very important in computer science. These algorithms have direct applications in searching algorithms, database algorithms, divide and conquer methods, data structure algorithms, and many more.

Trade-Offs of Sorting Algorithms
When choosing a sorting algorithm, some questions have to be asked – How big is the collection being sorted? How much memory is available? Does the collection need to grow?

The answers to these questions may determine which algorithm is going to work best for each situation. Some algorithms like merge sort may need a lot of space or memory to run, while insertion sort is not always the fastest, but doesn't require many resources to run.

You should determine what your requirements are, and consider the limitations of your system before deciding which sorting algorithm to use.

Some Common Sorting Algorithms
Some of the most common sorting algorithms are:

Selection sort
Bubble sort
Insertion sort
Merge sort
Quick sort
Heap sort
Counting sort
Radix sort
Bucket sort
But before we get into each of these, let's learn a bit more about what classifies a sorting algorithm.

Classification of a Sorting Algorithm
Sorting algorithms can be categorized based on the following parameters:

The number of swaps or inversions required: This is the number of times the algorithm swaps elements to sort the input. Selection sort requires the minimum number of swaps.
The number of comparisons: This is the number of times the algorithm compares elements to sort the input. Using [Big-O notation](https://guide.freecodecamp.org/computer-science/notation/big-o-notation/), the sorting algorithm examples listed above require at least O(nlogn) comparisons in the best case, and O(n^2) comparisons in the worst case for most of the outputs.
Whether or not they use recursion: Some sorting algorithms, such as quick sort, use recursive techniques to sort the input. Other sorting algorithms, such as selection sort or insertion sort, use non-recursive techniques. Finally, some sorting algorithms, such as merge sort, make use of both recursive as well as non-recursive techniques to sort the input.
Whether they are stable or unstable: Stable sorting algorithms maintain the relative order of elements with equal values, or keys. Unstable sorting algorithms do not maintain the relative order of elements with equal values / keys.

For example, imagine you have the input array [1, 2, 3, 2, 4]. And to help differentiate between the two equal values, 2, let's update them to 2a and 2b, making the input array [1, 2a, 3, 2b, 4].

Stable sorting algorithms will maintain the order of 2a and 2b, meaning the output array will be [1, 2a, 2b, 3, 4]. Unstable sorting algorithms do not maintain the order of equal values, and the output array may be [1, 2b, 2a, 3, 4].

Insertion sort, merge sort, and bubble sort are stable. Heap sort and quick sort are unstable.
The amount of extra space required: Some sorting algorithms can sort a list without creating an entirely new list. These are known as in-place sorting algorithms, and require a constant O(1) extra space for sorting. Meanwhile, out of place sorting algorithms create a new list while sorting.

Insertion sort and quick sort are in place sorting algorithms, as elements are moved around a pivot point, and do not use a separate array.

Merge sort is an example of an out of place sorting algorithm, as the size of the input must be allocated beforehand to store the output during the sort process, which requires extra memory.

**Comment by Soumelee** [comment]
> [Learn to code — free 3,000-hour curriculum](https://www.freecodecamp.org/)
> 
> DECEMBER 4, 2019 / [#ALGORITHMS](https://www.freecodecamp.org/news/tag/algorithms/) Sorting Algorithms Explained with Examples in JavaScript, Python, Java, and C++ What is a Sorting Algorithm? Sorting algorithms are a set of instructions that take an array or list as an input and arrange the items into a particular order.
> 
> Sorts are most commonly in numerical or a form of alphabetical (or lexicographical) order, and can be in ascending (A-Z, 0-9) or descending (Z-A, 9-0) order.
> 
> Why Sorting Algorithms are Important Since they can often reduce the complexity of a problem, sorting algorithms are very important in computer science. These algorithms have direct applications in searching algorithms, database algorithms, divide and conquer methods, data structure algorithms, and many more.
> 
> Trade-Offs of Sorting Algorithms When choosing a sorting algorithm, some questions have to be asked – How big is the collection being sorted? How much memory is available? Does the collection need to grow?
> 
> The answers to these questions may determine which algorithm is going to work best for each situation. Some algorithms like merge sort may need a lot of space or memory to run, while insertion sort is not always the fastest, but doesn't require many resources to run.
> 
> You should determine what your requirements are, and consider the limitations of your system before deciding which sorting algorithm to use.
> 
> Some Common Sorting Algorithms Some of the most common sorting algorithms are:
> 
> Selection sort Bubble sort Insertion sort Merge sort Quick sort Heap sort Counting sort Radix sort Bucket sort But before we get into each of these, let's learn a bit more about what classifies a sorting algorithm.
> 
> Classification of a Sorting Algorithm Sorting algorithms can be categorized based on the following parameters:
> 
> The number of swaps or inversions required: This is the number of times the algorithm swaps elements to sort the input. Selection sort requires the minimum number of swaps. The number of comparisons: This is the number of times the algorithm compares elements to sort the input. Using [Big-O notation](https://guide.freecodecamp.org/computer-science/notation/big-o-notation/), the sorting algorithm examples listed above require at least O(nlogn) comparisons in the best case, and O(n^2) comparisons in the worst case for most of the outputs. Whether or not they use recursion: Some sorting algorithms, such as quick sort, use recursive techniques to sort the input. Other sorting algorithms, such as selection sort or insertion sort, use non-recursive techniques. Finally, some sorting algorithms, such as merge sort, make use of both recursive as well as non-recursive techniques to sort the input. Whether they are stable or unstable: Stable sorting algorithms maintain the relative order of elements with equal values, or keys. Unstable sorting algorithms do not maintain the relative order of elements with equal values / keys.
> 
> For example, imagine you have the input array [1, 2, 3, 2, 4]. And to help differentiate between the two equal values, 2, let's update them to 2a and 2b, making the input array [1, 2a, 3, 2b, 4].
> 
> Stable sorting algorithms will maintain the order of 2a and 2b, meaning the output array will be [1, 2a, 2b, 3, 4]. Unstable sorting algorithms do not maintain the order of equal values, and the output array may be [1, 2b, 2a, 3, 4].
> 
> Insertion sort, merge sort, and bubble sort are stable. Heap sort and quick sort are unstable. The amount of extra space required: Some sorting algorithms can sort a list without creating an entirely new list. These are known as in-place sorting algorithms, and require a constant O(1) extra space for sorting. Meanwhile, out of place sorting algorithms create a new list while sorting.
> 
> Insertion sort and quick sort are in place sorting algorithms, as elements are moved around a pivot point, and do not use a separate array.
> 
> Merge sort is an example of an out of place sorting algorithm, as the size of the input must be allocated beforehand to store the output during the sort process, which requires extra memory.

@anamikapanda 
The texts should go along with the animation that is occurring. The link must be there bw what they are seeing and what they are reading. This is already available on the internet anybody can google it, as you have done.

**Comment by anamikapanda** [comment]
just read about using @keyframes in CSS properties which defines the code for animation.
@keyframes animationname {keyframes-selector{css-styles;}}
